import {
  faClose,
  faEnvelope,
  faEye,
  faFeather,
  faHashtag,
  faMagnifyingGlass,
  faNewspaper,
  faPenToSquare,
  faPlus,
  faTags,
  faTrash,
  faUserPlus,
  faUsers,
} from "@fortawesome/free-solid-svg-icons";

export const icons = {
  users: faUsers,
  addUser: faUserPlus,
  add: faPlus,
  delete: faTrash,
  close: faClose,
  search: faMagnifyingGlass,
  update: faPenToSquare,
  tags: faHashtag,
  category: faTags,
  author: faFeather,
  view: faEye,
  email: faEnvelope,
  posts: faNewspaper,
};
